### ISSUE TITLE
Installation and production usage

### ISSUE THREAD

**Issue by amit777** [titusjose/postfix_redis#1]
Hi, I was looking for a redis map and came across this project.  Is this actively used in production by yourself?

**Comment by titusjose** [comment]
Hi amit777,

Its been a while since I stopped maintaining this. However if you do have use case that is compelling to use a redis map than a tcp map via a broker, do tell me, I can continue supporting this.

**Comment by amit777** [comment]
I've started using a tcp map. Thanks for the tip!
